### ISSUE TITLE
Crash when trying to scan a whole disk

### ISSUE THREAD

**Issue by modmuss50** [trebonius0/Phototo#17]
https://gist.github.com/modmuss50/27ab8a8386850a1fe5030f2ad9c1d149

This is being ran as the system administrator on Windows Server 2016. Latest java 8 runtime.

Edit: works when scanning a sub dir, only when given a whole volume it fails.

**Comment by trebonius0** [comment]
Could you try with "e:\" instead of "e:" ?

**Comment by modmuss50** [comment]
https://gist.github.com/modmuss50/419ffba77223f51fd7c691dde0bccdca

**Comment by modmuss50** [comment]
Doing `E:\\` Causes the same crash as the first one.

**Comment by trebonius0** [comment]
Thanks
Bug has been fixed (Commit c083c010bc55c0093b3c42f6718efcae4a3225fb)
