### ISSUE TITLE
Photos not being correctly orientated.

### ISSUE THREAD

**Issue by modmuss50** [trebonius0/Phototo#19]
![mstsc_2017-01-21_17-00-30](https://cloud.githubusercontent.com/assets/4324090/22176139/3dc47ef2-dffb-11e6-997f-3bc7ffedddca.jpg)

When looking at the photo in windows photo viewer it has been rotated. When looking on the website it hasnt

**Comment by trebonius0** [comment]
Can't repro the problem. Could you send me the picture (trebonius@worldofwargraphs.com)

Thanks !
